# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token ebd94db974ac57b2970be3fca7c707a636198198

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/3/
Content-Type: application/json
Authorization: Token ebd94db974ac57b2970be3fca7c707a636198198

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?status=CLOSED
Content-Type: application/json

###

DELETE {{baseUrl}}/advertisements/1/
Authorization: Token cdbce7bdfe1ac624dd8e7554d6ee8983e4c0374d
Content-Type: application/json

###

POST {{baseUrl}}/advertisements/2/add_favorite/
Authorization: Token cdbce7bdfe1ac624dd8e7554d6ee8983e4c0374d
Content-Type: application/json

###

GET {{baseUrl}}/advertisements/?is_favorite=True
Authorization: Token cdbce7bdfe1ac624dd8e7554d6ee8983e4c0374d
Content-Type: application/json

###

POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token cdbce7bdfe1ac624dd8e7554d6ee8983e4c0374d

{
  "title": "Полка IKEA",
  "description": "Куплю"
}

###

PATCH {{baseUrl}}/advertisements/17/
Content-Type: application/json
Authorization: Token cdbce7bdfe1ac624dd8e7554d6ee8983e4c0374d

{
  "status": "DRAFT"
}